//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.MIS_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMMaster
    {
        public int ID { get; set; }
        public string BOMID { get; set; }
        public System.DateTime BOMDate { get; set; }
        public Nullable<int> CommercialProductID { get; set; }
        public string CommercialCode { get; set; }
        public string ProductID { get; set; }
        public decimal BatchQty { get; set; }
        public string BatchUOM { get; set; }
        public decimal BatchWeight { get; set; }
        public string BatchWeightUOM { get; set; }
        public decimal TheoOutput { get; set; }
        public string TheoOutputUOM { get; set; }
        public decimal StdOutput { get; set; }
        public string StdOutputUOM { get; set; }
        public Nullable<decimal> APIPhilarWeight { get; set; }
        public string APIPhilarUOM { get; set; }
        public string APIPhilarM { get; set; }
        public bool IsInActive { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
