//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.MIS_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotAndSalesLocationMapping
    {
        public int ID { get; set; }
        public Nullable<int> DepotLocationID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
