//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.MIS_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ProductionPlanning_MaterialDetails
    {
        public int ID { get; set; }
        public int DetailsID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<decimal> TotalBatchQuantity { get; set; }
        public Nullable<decimal> FreeStock { get; set; }
        public Nullable<decimal> RequisitionQuantity { get; set; }
        public Nullable<decimal> BookingQuantity { get; set; }
        public Nullable<decimal> QuarantineQuantity { get; set; }
    
        public virtual Inventory_ProductionPlanning_Details Inventory_ProductionPlanning_Details { get; set; }
    }
}
