//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.MIS_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ProductionPlanning_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_ProductionPlanning_Master()
        {
            this.Inventory_ProductionPlanning_Details = new HashSet<Inventory_ProductionPlanning_Details>();
        }
    
        public int MPSID { get; set; }
        public string MPSCode { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public int BatchInProgress { get; set; }
        public int TotalBatchRequired { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<decimal> ShortagePercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_ProductionPlanning_Details> Inventory_ProductionPlanning_Details { get; set; }
    }
}
