//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.MIS_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncEventLog
    {
        public int SyncId { get; set; }
        public string ProcedureName { get; set; }
        public string LogDetails { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
