//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> IsTopBrand { get; set; }
        public Nullable<bool> ShowingStatus { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
