//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailSchedule()
        {
            this.EmailSchedule_Recepient = new HashSet<EmailSchedule_Recepient>();
            this.EmailSchedule_Schedule = new HashSet<EmailSchedule_Schedule>();
        }
    
        public int ID { get; set; }
        public string ScheduleName { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContent { get; set; }
        public string URL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TagName { get; set; }
        public string AttachmentFilename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSchedule_Recepient> EmailSchedule_Recepient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSchedule_Schedule> EmailSchedule_Schedule { get; set; }
    }
}
