//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSchedule_Recepient
    {
        public int ID { get; set; }
        public Nullable<int> EmailScheduleID { get; set; }
        public string RecepientEmployeeID { get; set; }
    
        public virtual EmailSchedule EmailSchedule { get; set; }
    }
}
