//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSchedule_Schedule
    {
        public int ID { get; set; }
        public Nullable<int> EmailScheduleID { get; set; }
        public Nullable<bool> IsDaily { get; set; }
        public Nullable<bool> IsWeekly { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
        public Nullable<bool> Satureday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<byte> Hour1 { get; set; }
        public Nullable<byte> Hour2 { get; set; }
        public Nullable<byte> Hour3 { get; set; }
        public string LastExecutionID { get; set; }
    
        public virtual EmailSchedule EmailSchedule { get; set; }
    }
}
