//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> CardNo { get; set; }
        public string Salutation { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string NickName { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public System.DateTime DOB { get; set; }
        public string JoiningPosition { get; set; }
        public Nullable<int> JoiningPositionID { get; set; }
        public Nullable<int> EmployeePositionID { get; set; }
        public string BloodGroup { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Sex { get; set; }
        public string MaritalStatus { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string NationalIDNo { get; set; }
        public string EPersonName { get; set; }
        public string EPersonAddress { get; set; }
        public string EPersonTelephone { get; set; }
        public string EmployeeStatus { get; set; }
        public string EmployeeType { get; set; }
        public string CompanyID { get; set; }
        public string Department { get; set; }
        public string SubDepartment { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string Zone { get; set; }
        public string Region { get; set; }
        public string Area { get; set; }
        public string Territory { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string JoiningGrade { get; set; }
        public string AcademicAward { get; set; }
        public string DrivingLicence { get; set; }
        public string Passport { get; set; }
        public string VisitCountry { get; set; }
        public string ExtraActivities { get; set; }
        public string MajorIllness { get; set; }
        public string SuperVisorID { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ConfirmationStatus { get; set; }
        public bool Certification { get; set; }
        public Nullable<System.DateTime> LastAppDate { get; set; }
        public string LastAppType { get; set; }
        public string CostCenter { get; set; }
        public string Remarks { get; set; }
        public string LeaveRuleID { get; set; }
        public string MachineNameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
