//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string ExceptionTitle { get; set; }
        public string ExceptionDetails { get; set; }
        public string ReportedByID { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Route { get; set; }
        public Nullable<bool> IsAutoGenerated { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    }
}
