//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ProductionPlanning_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_ProductionPlanning_Details()
        {
            this.Inventory_ProductionPlanning_MaterialDetails = new HashSet<Inventory_ProductionPlanning_MaterialDetails>();
        }
    
        public int ID { get; set; }
        public int MPSID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> BatchUnitQuantity { get; set; }
        public Nullable<int> DayCoverForecast { get; set; }
        public Nullable<int> DayCoverSale { get; set; }
        public Nullable<int> ForecastMonth1CommercialQty { get; set; }
        public Nullable<int> ForecastMonth1SampleQty { get; set; }
        public Nullable<int> ForecastMonth2CommercialQty { get; set; }
        public Nullable<int> ForecastMonth2SampleQty { get; set; }
        public Nullable<int> ForecastCurrentMonthCommercialQty { get; set; }
        public Nullable<int> ForecastCurrentMonthSampleQty { get; set; }
        public Nullable<int> ForecastMonth3SampleQty { get; set; }
        public Nullable<int> ForecastMonth3CommercialQty { get; set; }
        public Nullable<int> LastMonthSalesQty { get; set; }
        public Nullable<int> NoOfBatchRequired { get; set; }
        public Nullable<int> NoOfBatchRequiredOutput { get; set; }
        public Nullable<int> SalesUptoQty { get; set; }
        public Nullable<int> TotalBatchInProgress { get; set; }
        public Nullable<int> TotalBatchOutputInProgress { get; set; }
        public Nullable<int> TotalFreeStock { get; set; }
        public Nullable<int> TotalInProgress { get; set; }
        public Nullable<int> TotalQuantityDayCoverForecast { get; set; }
        public Nullable<int> TotalQuantityDayCoverSale { get; set; }
        public Nullable<int> TwoMonthsAgoSalesQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_ProductionPlanning_MaterialDetails> Inventory_ProductionPlanning_MaterialDetails { get; set; }
        public virtual Inventory_ProductionPlanning_Master Inventory_ProductionPlanning_Master { get; set; }
    }
}
