//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationWiseSale
    {
        public long ID { get; set; }
        public int BrandId { get; set; }
        public int ZoneId { get; set; }
        public int RegionId { get; set; }
        public int AreaId { get; set; }
        public int TerritoryID { get; set; }
        public int ProductId { get; set; }
        public int YearNo { get; set; }
        public int MonthNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<decimal> SoldValue { get; set; }
    }
}
