//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaintenanceEntities : DbContext
    {
        public MaintenanceEntities()
            : base("name=MaintenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<EmailSchedule> EmailSchedules { get; set; }
        public virtual DbSet<EmailSchedule_Recepient> EmailSchedule_Recepient { get; set; }
        public virtual DbSet<EmailSchedule_Schedule> EmailSchedule_Schedule { get; set; }
        public virtual DbSet<Validation_Logs> Validation_Logs { get; set; }
    }
}
