//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_PurchaseTimeline
    {
        public int ID { get; set; }
        public string MaterialCode { get; set; }
        public string Code { get; set; }
        public string VersionNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Remarks { get; set; }
        public string Step { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> EventDays { get; set; }
        public string RequisitionCode { get; set; }
    }
}
