//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string ProductionLocation { get; set; }
        public string ProductCode { get; set; }
        public string CompanyID { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> ProductPriorityID { get; set; }
        public string ProductForm { get; set; }
        public string DosageForm { get; set; }
        public string GenericName { get; set; }
        public string DarNo { get; set; }
        public string PackSize { get; set; }
        public string UOM { get; set; }
        public string SalesCode { get; set; }
        public string PPS { get; set; }
        public string SPS { get; set; }
        public string MPS { get; set; }
        public string Strength { get; set; }
        public Nullable<decimal> TP { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> VatPayable { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> ShelfMonth { get; set; }
        public Nullable<int> ShelfYear { get; set; }
        public Nullable<int> ProductionLeadTime { get; set; }
        public Nullable<int> QALeadTime { get; set; }
        public Nullable<int> QAValidLeadTime { get; set; }
        public Nullable<int> QAComLeadTime { get; set; }
        public Nullable<int> QATenBatchLeadTime { get; set; }
        public Nullable<int> QAReleaseValidLeadTime { get; set; }
        public Nullable<int> QAReleaseComLeadTime { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public Nullable<bool> ShowingStatus { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
