using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using WebERPAPI.BusinessLogic.InventoryNonProduction;
using WebERPAPI.DTO;
using WebERPAPI.DTO.Inventory.Procurement;
using WebERPAPI.Data.Models.PROCESSERVER;

namespace WebERPAPI.BusinessLogic.Test
{
    /// <summary>
    /// Summary description for RequisitionNonProductionTest
    /// </summary>
    [TestClass]
    public class RequisitionNPTest
    {
        private RequisitionNP service = new RequisitionNP();

        private string EmployeeId = "LPL02693";
        private string ItemCode = "";
        private int ItemID = 13;
        private int RequisitionId = 0;

        public RequisitionNPTest()
        {
            //
            // TODO: Add constructor logic here
            //
        }

        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>

        #region GetMethods

        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        [TestMethod()]
        public void getItemReport()
        {
            int success = 0;

            var item = service.getItemReport(13, "0");
            if (item != null) success++;

            var item2 = service.getItemReport(15, "0");
            if (item2 != null) success++;

            var item3 = service.getItemReport(17, "0");
            if (item3 != null) success++;

            Assert.IsTrue(success > 0);
        }

        [TestMethod()]
        public void getRequisitionDetails()
        {
            int success = 0;

            RequisitionId = 3;
            var item = service.getRequisitionDetails(RequisitionId);
            if (item != null) success++;

            RequisitionId = 5;
            var item2 = service.getRequisitionDetails(RequisitionId);
            if (item2 != null) success++;

            RequisitionId = 6;
            var item3 = service.getRequisitionDetails(RequisitionId);
            if (item3 != null) success++;

            Assert.IsTrue(success > 0);
        }

        [TestMethod()]
        public void getItemUOM()
        {
            Assert.IsNotNull(service.getItemUOM());
        }

        [TestMethod()]
        public void getInventoryRequisitionForBrands()
        {
            int success = 0;

            RequisitionId = 8;
            string brands = service.getInventoryRequisitionForBrands(RequisitionId);
            if (!string.IsNullOrEmpty(brands)) success++;

            Assert.IsTrue(success > 0);
        }

        [TestMethod()]
        public void getInventoryRequisitionForMonths()
        {
            int success = 0;

            RequisitionId = 8;
            string brands = service.getInventoryRequisitionForMonths(RequisitionId);
            if (!string.IsNullOrEmpty(brands)) success++;

            Assert.IsTrue(success > 0);
        }

        [TestMethod()]
        public void getRequisitionReport()
        {
            int success = 0;

            RequisitionId = 3;
            var item = service.getRequisitionReport("0", RequisitionId);
            if (item != null) success++;

            RequisitionId = 5;
            var item2 = service.getRequisitionReport("0", RequisitionId);
            if (item2 != null) success++;

            RequisitionId = 6;
            var item3 = service.getRequisitionReport("0", RequisitionId);
            if (item3 != null) success++;

            Assert.IsTrue(success > 0);
        }

        #endregion GetMethods

        #region CreateMethods

       
        [TestMethod()]
        public void createInventoryRequisitionTest()
        {
            InventoryRequisitionNew data = new InventoryRequisitionNew();
            data.BrandIds = "test brand";
            data.Data = "W3siTWFpbkdyb3VwSUQiOjQ1LCJJdGVtSUQiOjgsIlN1Ykdyb3VwSUQiOjMsIlN1Ykdyb3VwTmFtZSI6IkRlc2t0b3AgUkFNIiwiSXRlbUNvZGUiOiJDQURSMDAwMiIsIkl0ZW1OYW1lIjoiUkFNIiwiSXRlbU5hbWVXaXRoU3BlYyI6IlJBTSAxNiBHQiIsIlVPTSI6IkdCIiwiTU9RIjoxLCJPcmRlck5vIjoxLCJWZXJzaW9uSUQiOjgsIlZlcnNpb25ObyI6MSwiUXVhbnRpdHkiOiIzIiwiRGVsaXZlcnlEYXRlIjoiMjAyMC0wMi0wNCIsIlB1cnBvc2UiOiJ0ZXN0IiwiU3BlY2lmaWNhdGlvbiI6W3siU3BlY2lmaWNhdGlvbklEIjoyNCwiU3BlY2lmaWNhdGlvblZhbHVlIjoiMTYiLCJTcGVjaWZpY2F0aW9uTmFtZSI6Ik1lbW9yeSIsIlVPTSI6IkdCIiwiU2hvd0luTmFtZSI6dHJ1ZSwiSXNTZWxlY3RlZCI6dHJ1ZSwiT3JkZXJObyI6MH0seyJTcGVjaWZpY2F0aW9uSUQiOjEsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJBbHUgdGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJhdGNoIFByaW50IEFyZWEiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiQnVybmlzaCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJDb2xvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJFbWJvc3MvRW5ncmF2ZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjo2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRmxpcCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJGb2xkaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6OCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkhlaWdodCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMYWNxdWVyIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGFtaW5hdGlvbiIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjExLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGVuZ3RoIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMaW5lciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTWljcm9uIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJPcGVuaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJQYXBlciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjE2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUGFwZXIgUGx5IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJSZXZlcnNlIFByaW50IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTgsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTaXplIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJUaGluIEZpbG0gTGFjcXVlciBUaGlja25lc3MiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlRvdGFsIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjIxLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiVG90YWwgVGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MjIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJXaWR0aCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI1LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiU3BlZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyNiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJVUyBTcGVlZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUG93ZXIiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlc29sdXRpb24iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlZW0iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMyLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiV2F0dCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUkFNIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTU0QiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozNSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdyYXBoaWNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzYsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJCcmFuZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTW9kZWwiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlByb2Nlc3NvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM5LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRGlzcGxheSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiSGFyZCBEaXNrIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfV19XQ==";
            data.EmployeeID = "LPL05360";
            data.InventoryTypeID = 5;
            data.MainGroupID = 2;
            data.RequisitionCode = "Test001";
            data.RequisitionTypeID = 1;
            data.StoreID = 2;
            Inventory_Requisitions result = service.createInventoryRequisition(data);
            Assert.IsNotNull(result, service.Error.Message);
            Assert.IsTrue(result.ID > 0);
        }

        [TestMethod()]
        public void updateInventoryRequisitionTest()
        {
            InventoryRequisitionNew data = new InventoryRequisitionNew();
            data.BrandIds = "test brand";
            data.Data = "W3siTWFpbkdyb3VwSUQiOjQ1LCJJdGVtSUQiOjgsIlN1Ykdyb3VwSUQiOjMsIlN1Ykdyb3VwTmFtZSI6IkRlc2t0b3AgUkFNIiwiSXRlbUNvZGUiOiJDQURSMDAwMiIsIkl0ZW1OYW1lIjoiUkFNIiwiSXRlbU5hbWVXaXRoU3BlYyI6IlJBTSAxNiBHQiIsIlVPTSI6IkdCIiwiTU9RIjoxLCJPcmRlck5vIjoxLCJWZXJzaW9uSUQiOjgsIlZlcnNpb25ObyI6MSwiUXVhbnRpdHkiOiIzIiwiRGVsaXZlcnlEYXRlIjoiMjAyMC0wMi0wNCIsIlB1cnBvc2UiOiJ0ZXN0IiwiU3BlY2lmaWNhdGlvbiI6W3siU3BlY2lmaWNhdGlvbklEIjoyNCwiU3BlY2lmaWNhdGlvblZhbHVlIjoiMTYiLCJTcGVjaWZpY2F0aW9uTmFtZSI6Ik1lbW9yeSIsIlVPTSI6IkdCIiwiU2hvd0luTmFtZSI6dHJ1ZSwiSXNTZWxlY3RlZCI6dHJ1ZSwiT3JkZXJObyI6MH0seyJTcGVjaWZpY2F0aW9uSUQiOjEsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJBbHUgdGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJhdGNoIFByaW50IEFyZWEiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiQnVybmlzaCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJDb2xvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJFbWJvc3MvRW5ncmF2ZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjo2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRmxpcCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJGb2xkaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6OCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkhlaWdodCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMYWNxdWVyIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGFtaW5hdGlvbiIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjExLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGVuZ3RoIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMaW5lciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTWljcm9uIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJPcGVuaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJQYXBlciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjE2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUGFwZXIgUGx5IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJSZXZlcnNlIFByaW50IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTgsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTaXplIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJUaGluIEZpbG0gTGFjcXVlciBUaGlja25lc3MiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlRvdGFsIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjIxLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiVG90YWwgVGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MjIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJXaWR0aCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI1LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiU3BlZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyNiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJVUyBTcGVlZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUG93ZXIiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlc29sdXRpb24iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlZW0iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMyLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiV2F0dCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUkFNIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTU0QiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozNSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdyYXBoaWNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzYsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJCcmFuZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTW9kZWwiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlByb2Nlc3NvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM5LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRGlzcGxheSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiSGFyZCBEaXNrIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfV19XQ==";
            data.EmployeeID = "LPL05360";
            data.ID = 42;
            data.InventoryTypeID = 5;
            data.MainGroupID = 2;
            data.RequisitionCode = "Test001";
            data.RequisitionTypeID = 1;
            data.StoreID = 2;
            Inventory_Requisitions result = service.updateInventoryRequisition(data);
            Assert.IsNotNull(result, service.Error.Message);
            Assert.IsTrue(result.ID > 0);
        }

        [TestMethod()]
        public void deleteInventoryItemTest()
        {
            InventoryRequisitionNew data = new InventoryRequisitionNew();
            data.BrandIds = "test brand";
            data.Data = "W3siTWFpbkdyb3VwSUQiOjQ1LCJJdGVtSUQiOjgsIlN1Ykdyb3VwSUQiOjMsIlN1Ykdyb3VwTmFtZSI6IkRlc2t0b3AgUkFNIiwiSXRlbUNvZGUiOiJDQURSMDAwMiIsIkl0ZW1OYW1lIjoiUkFNIiwiSXRlbU5hbWVXaXRoU3BlYyI6IlJBTSAxNiBHQiIsIlVPTSI6IkdCIiwiTU9RIjoxLCJPcmRlck5vIjoxLCJWZXJzaW9uSUQiOjgsIlZlcnNpb25ObyI6MSwiUXVhbnRpdHkiOiIzIiwiRGVsaXZlcnlEYXRlIjoiMjAyMC0wMi0wNCIsIlB1cnBvc2UiOiJ0ZXN0IiwiU3BlY2lmaWNhdGlvbiI6W3siU3BlY2lmaWNhdGlvbklEIjoyNCwiU3BlY2lmaWNhdGlvblZhbHVlIjoiMTYiLCJTcGVjaWZpY2F0aW9uTmFtZSI6Ik1lbW9yeSIsIlVPTSI6IkdCIiwiU2hvd0luTmFtZSI6dHJ1ZSwiSXNTZWxlY3RlZCI6dHJ1ZSwiT3JkZXJObyI6MH0seyJTcGVjaWZpY2F0aW9uSUQiOjEsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJBbHUgdGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJhdGNoIFByaW50IEFyZWEiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiQnVybmlzaCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJDb2xvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJFbWJvc3MvRW5ncmF2ZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjo2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRmxpcCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJGb2xkaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6OCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkhlaWdodCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMYWNxdWVyIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGFtaW5hdGlvbiIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjExLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGVuZ3RoIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMaW5lciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTWljcm9uIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJPcGVuaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJQYXBlciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjE2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUGFwZXIgUGx5IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJSZXZlcnNlIFByaW50IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTgsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTaXplIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJUaGluIEZpbG0gTGFjcXVlciBUaGlja25lc3MiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlRvdGFsIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjIxLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiVG90YWwgVGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MjIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJXaWR0aCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI1LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiU3BlZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyNiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJVUyBTcGVlZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUG93ZXIiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlc29sdXRpb24iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlZW0iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMyLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiV2F0dCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUkFNIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTU0QiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozNSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdyYXBoaWNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzYsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJCcmFuZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTW9kZWwiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlByb2Nlc3NvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM5LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRGlzcGxheSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiSGFyZCBEaXNrIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfV19XQ==";
            data.EmployeeID = "LPL05360";
            data.ID = 42;
            data.InventoryTypeID = 5;
            data.MainGroupID = 2;
            data.RequisitionCode = "Test001";
            data.RequisitionTypeID = 1;
            data.StoreID = 2;
            Inventory_Items result = service.deleteInventoryItem(42, "LPL05360");
            Assert.IsNotNull(result, service.Error.Message);
            Assert.IsTrue(result.ID > 0);
        }

        [TestMethod()]
        public void verifyInventoryRequisitionTest()
        {
            CommonDataEntryClass data = new CommonDataEntryClass();
            data.Quantity = 3;
            data.Data = "W3siTWFpbkdyb3VwSUQiOjQ1LCJJdGVtSUQiOjgsIlN1Ykdyb3VwSUQiOjMsIlN1Ykdyb3VwTmFtZSI6IkRlc2t0b3AgUkFNIiwiSXRlbUNvZGUiOiJDQURSMDAwMiIsIkl0ZW1OYW1lIjoiUkFNIiwiSXRlbU5hbWVXaXRoU3BlYyI6IlJBTSAxNiBHQiIsIlVPTSI6IkdCIiwiTU9RIjoxLCJPcmRlck5vIjoxLCJWZXJzaW9uSUQiOjgsIlZlcnNpb25ObyI6MSwiUXVhbnRpdHkiOiIzIiwiRGVsaXZlcnlEYXRlIjoiMjAyMC0wMi0wNCIsIlB1cnBvc2UiOiJ0ZXN0IiwiU3BlY2lmaWNhdGlvbiI6W3siU3BlY2lmaWNhdGlvbklEIjoyNCwiU3BlY2lmaWNhdGlvblZhbHVlIjoiMTYiLCJTcGVjaWZpY2F0aW9uTmFtZSI6Ik1lbW9yeSIsIlVPTSI6IkdCIiwiU2hvd0luTmFtZSI6dHJ1ZSwiSXNTZWxlY3RlZCI6dHJ1ZSwiT3JkZXJObyI6MH0seyJTcGVjaWZpY2F0aW9uSUQiOjEsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJBbHUgdGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJhdGNoIFByaW50IEFyZWEiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiQnVybmlzaCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJDb2xvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJFbWJvc3MvRW5ncmF2ZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjo2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRmxpcCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJGb2xkaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6OCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkhlaWdodCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMYWNxdWVyIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGFtaW5hdGlvbiIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjExLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTGVuZ3RoIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJMaW5lciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjEzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTWljcm9uIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJPcGVuaW5nIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTUsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJQYXBlciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjE2LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUGFwZXIgUGx5IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTcsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJSZXZlcnNlIFByaW50IiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTgsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTaXplIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MTksIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJUaGluIEZpbG0gTGFjcXVlciBUaGlja25lc3MiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlRvdGFsIEdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjIxLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiVG90YWwgVGhpY2tuZXNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MjIsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJXaWR0aCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI1LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiU3BlZWQiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyNiwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkJVUyBTcGVlZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjI3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUG93ZXIiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjoyOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlc29sdXRpb24iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlJlZW0iLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozMSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdTTSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMyLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiV2F0dCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjMzLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiUkFNIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzQsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJTU0QiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozNSwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IkdyYXBoaWNzIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfSx7IlNwZWNpZmljYXRpb25JRCI6MzYsIlNwZWNpZmljYXRpb25WYWx1ZSI6bnVsbCwiU3BlY2lmaWNhdGlvbk5hbWUiOiJCcmFuZCIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM3LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiTW9kZWwiLCJVT00iOm51bGwsIlNob3dJbk5hbWUiOm51bGwsIklzU2VsZWN0ZWQiOm51bGwsIk9yZGVyTm8iOm51bGx9LHsiU3BlY2lmaWNhdGlvbklEIjozOCwiU3BlY2lmaWNhdGlvblZhbHVlIjpudWxsLCJTcGVjaWZpY2F0aW9uTmFtZSI6IlByb2Nlc3NvciIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjM5LCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiRGlzcGxheSIsIlVPTSI6bnVsbCwiU2hvd0luTmFtZSI6bnVsbCwiSXNTZWxlY3RlZCI6bnVsbCwiT3JkZXJObyI6bnVsbH0seyJTcGVjaWZpY2F0aW9uSUQiOjQwLCJTcGVjaWZpY2F0aW9uVmFsdWUiOm51bGwsIlNwZWNpZmljYXRpb25OYW1lIjoiSGFyZCBEaXNrIiwiVU9NIjpudWxsLCJTaG93SW5OYW1lIjpudWxsLCJJc1NlbGVjdGVkIjpudWxsLCJPcmRlck5vIjpudWxsfV19XQ==";
            data.ItemName = "test";
            data.ID = 42;
            data.TypeID = 1;
            data.Remarks = "Unit test";
            data.ActionGroupID = 2;
            data.Date = DateTime.Now;
            data.EmployeeCode = "LPL05360";
            Inventory_Requisitions result = service.verifyInventoryRequisition(2, data);
            Assert.IsNotNull(result, service.Error.Message);
            Assert.IsTrue(result.ID > 0);
        }
        #endregion CreateMethods

        #region Additional test attributes

        //
        // You can use the following additional attributes as you write your tests:
        //
        // Use ClassInitialize to run code before running the first test in the class
        // [ClassInitialize()]
        // public static void MyClassInitialize(TestContext testContext) { }
        //
        // Use ClassCleanup to run code after all tests in a class have run
        // [ClassCleanup()]
        // public static void MyClassCleanup() { }
        //
        // Use TestInitialize to run code before running each test
        // [TestInitialize()]
        // public void MyTestInitialize() { }
        //
        // Use TestCleanup to run code after each test has run
        // [TestCleanup()]
        // public void MyTestCleanup() { }
        //

        #endregion Additional test attributes
    }
}