using System;

namespace LabaidMIS.Data.Classes.Accounts.JournalVoucher
{
    public class VoucherMaster
    {
        public string RefNo { get; set; }

        public Nullable<DateTime> RefDate { get; set; }
        public string VoucherID { get; set; }
        public Nullable<DateTime> VoucherDate { get; set; }
        public string VoucherNo { get; set; }
        public string Narration { get; set; }

        public string CreatedBy { get; set; }
        public Nullable<DateTime> CreatedOn { get; set; }
        public Nullable<Boolean> IsAutoGenerated { get; set; }
    }

    public class VoucherDetails
    {
        public string ACode { get; set; }

        public string MainAccountCode { get; set; }
        public string MainHeadName { get; set; }
        public string MainAccountsTitle { get; set; }
        public string SubHeadName { get; set; }
        public string SubAccountsTitle { get; set; }

        public string CostCenterID { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string CostCenterName { get; set; }
    }

    public class GRNTransaction
    {
        public string ACode { get; set; }

        public string GRNID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LCID { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }

        public Nullable<decimal> QCQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
    }

    public class VATTransaction
    {
        public string VoucherID { get; set; }
        public string ChallanBLNo { get; set; }
        public Nullable<DateTime> ChallanBLDate { get; set; }
        public string LCNo { get; set; }
        public string ACode { get; set; }

        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
    }

    public class BillTransaction
    {
        public string ACode { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string PONo { get; set; }
        public string RefNo { get; set; }
        public Nullable<DateTime> RefDate { get; set; }

        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
    }

    public class JournalVoucherFooter
    {
        public string BillCode { get; set; }

        public string ReceivedBy { get; set; }
        public Nullable<DateTime> AccountsReceiveDate { get; set; }
        public string ReceivedByDesignation { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<DateTime> ReviewedOn { get; set; }

        public string ReviewedByDesignation { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<DateTime> VerifiedOn { get; set; }
        public string VerifiedByDesignation { get; set; }
        public string BillSubmittedBy { get; set; }
        public Nullable<DateTime> BillSubmittedOn { get; set; }
        public string BillSubmittedByDesignation { get; set; }
    }
}