//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDist
    {
        public string BillID { get; set; }
        public int SLNo { get; set; }
        public string ServiceType { get; set; }
        public string ServiceID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string LCDocumentNo { get; set; }
        public string InvoiceNo { get; set; }
        public string ItemName { get; set; }
        public string LoadingPoint { get; set; }
        public decimal DocumentValue { get; set; }
        public decimal BillAmount { get; set; }
        public decimal DiscountAmt { get; set; }
        public decimal NetPayableAmount { get; set; }
        public string OthersInfo { get; set; }
    
        public virtual BillMaster BillMaster { get; set; }
    }
}
