//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Payment_Advance
    {
        public int ID { get; set; }
        public string AdvancePaymentCode { get; set; }
        public string POID { get; set; }
        public Nullable<int> BillGroupTypeID { get; set; }
        public string SupplierID { get; set; }
        public Nullable<decimal> POAmount { get; set; }
        public Nullable<decimal> AdvancePercent { get; set; }
        public Nullable<decimal> AdvancePaymentAmount { get; set; }
        public Nullable<bool> IsReceivedFromAccounts { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
    }
}
