//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Payment_Details
    {
        public int PaymentID { get; set; }
        public string BillID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public string BankID { get; set; }
        public string CheckNo { get; set; }
        public string BankBranchName { get; set; }
        public string PaymentBy { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
