//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeMap
    {
        public string BulkCode { get; set; }
        public string CommercialCode { get; set; }
        public string SampleCode1 { get; set; }
        public string SampleCode2 { get; set; }
        public string SampleCode3 { get; set; }
    }
}
