//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparative_Study_Internal_Approval_Details
    {
        public int ID { get; set; }
        public int InternalApprovalID { get; set; }
        public int CSID { get; set; }
        public Nullable<bool> IsPurchaseOrderDone { get; set; }
        public string RequisitionCode { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Comparative_Study_Internal_Approval Comparative_Study_Internal_Approval { get; set; }
    }
}
