//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparative_Study_Internal_Approval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comparative_Study_Internal_Approval()
        {
            this.Comparative_Study_Internal_Approval_Details = new HashSet<Comparative_Study_Internal_Approval_Details>();
        }
    
        public int ID { get; set; }
        public string InternalApprovalCode { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comparative_Study_Internal_Approval_Details> Comparative_Study_Internal_Approval_Details { get; set; }
    }
}
