//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparative_Study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comparative_Study()
        {
            this.Comparative_Study_Details = new HashSet<Comparative_Study_Details>();
        }
    
        public int ID { get; set; }
        public string CSCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string ReasonToCanceled { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string RollBackByID { get; set; }
        public string RollBackRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comparative_Study_Details> Comparative_Study_Details { get; set; }
    }
}
