//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNDetail
    {
        public string GRNID { get; set; }
        public string MaterialCode { get; set; }
        public decimal Qty { get; set; }
        public string UOM { get; set; }
        public decimal ReceiveQty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> MFGDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string PackingInfo { get; set; }
        public string Damage { get; set; }
        public string RoomNo { get; set; }
        public string RackNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual GRNMaster GRNMaster { get; set; }
    }
}
