//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNMaster
    {
        public string GRNID { get; set; }
        public System.DateTime GRNDate { get; set; }
        public string ReceiveType { get; set; }
        public string SupplierID { get; set; }
        public string POID { get; set; }
        public string LCID { get; set; }
        public string ProjectCD { get; set; }
        public string IssueID { get; set; }
        public string QCPriority { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApproveComment { get; set; }
        public string Source { get; set; }
        public string StorageCondition { get; set; }
        public string Indication { get; set; }
        public string NoofConRec { get; set; }
        public string Status { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string CustomNo { get; set; }
        public string LocalBatchNo { get; set; }
        public string BatchID { get; set; }
        public bool IsVatChallan { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual GRNDetail GRNDetail { get; set; }
    }
}
