//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNVat
    {
        public string GRNID { get; set; }
        public string VatChallanNo { get; set; }
        public System.DateTime VatChallanDate { get; set; }
        public decimal ChallanAmount { get; set; }
    }
}
