//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill_GroupType> Bill_GroupType { get; set; }
        public virtual DbSet<Bill_Payment_Advance> Bill_Payment_Advance { get; set; }
        public virtual DbSet<Bill_Payment_Details> Bill_Payment_Details { get; set; }
        public virtual DbSet<Bill_Payment_Status> Bill_Payment_Status { get; set; }
        public virtual DbSet<Bill_PaymentType> Bill_PaymentType { get; set; }
        public virtual DbSet<BillDetail> BillDetails { get; set; }
        public virtual DbSet<Comparative_Study_Internal_Approval> Comparative_Study_Internal_Approval { get; set; }
        public virtual DbSet<Comparative_Study_Internal_Approval_Details> Comparative_Study_Internal_Approval_Details { get; set; }
        public virtual DbSet<GRNDetail> GRNDetails { get; set; }
        public virtual DbSet<LC> LCs { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<POReq> POReqs { get; set; }
        public virtual DbSet<POReqDetail> POReqDetails { get; set; }
        public virtual DbSet<PriorityStatu> PriorityStatus { get; set; }
        public virtual DbSet<Quotation_Invitation_Details> Quotation_Invitation_Details { get; set; }
        public virtual DbSet<Quotation_Invitations> Quotation_Invitations { get; set; }
        public virtual DbSet<Quotation_Received> Quotation_Received { get; set; }
        public virtual DbSet<Quotation_Received_Details> Quotation_Received_Details { get; set; }
        public virtual DbSet<Supplier_TDS> Supplier_TDS { get; set; }
        public virtual DbSet<RequisitionFollowUp> RequisitionFollowUps { get; set; }
        public virtual DbSet<IntermediateMaterialConversion> IntermediateMaterialConversions { get; set; }
        public virtual DbSet<DosageForm> DosageForms { get; set; }
        public virtual DbSet<ProductionLocation> ProductionLocations { get; set; }
        public virtual DbSet<ProductionScheduleIgnoredMaterial> ProductionScheduleIgnoredMaterials { get; set; }
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<ProductPriority> ProductPriorities { get; set; }
        public virtual DbSet<ProductProcess> ProductProcesses { get; set; }
        public virtual DbSet<ProcessDef> ProcessDefs { get; set; }
        public virtual DbSet<Challan_Approval_Request> Challan_Approval_Request { get; set; }
        public virtual DbSet<CodeMap> CodeMaps { get; set; }
        public virtual DbSet<PODetail> PODetails { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Quotation_Received_Import> Quotation_Received_Import { get; set; }
        public virtual DbSet<Quotation_Received_Import_Details> Quotation_Received_Import_Details { get; set; }
        public virtual DbSet<Comparative_Study_Import_InternalApproval> Comparative_Study_Import_InternalApproval { get; set; }
        public virtual DbSet<Comparative_Study_Import_InternalApproval_Details> Comparative_Study_Import_InternalApproval_Details { get; set; }
        public virtual DbSet<ProformaInvoice_Invitation> ProformaInvoice_Invitation { get; set; }
        public virtual DbSet<ProformaInvoice_Invitation_Details> ProformaInvoice_Invitation_Details { get; set; }
        public virtual DbSet<ProformaInvoice> ProformaInvoices { get; set; }
        public virtual DbSet<ProformaInvoice_Details> ProformaInvoice_Details { get; set; }
        public virtual DbSet<Proforma_BlockList> Proforma_BlockList { get; set; }
        public virtual DbSet<Proforma_BlockList_Details> Proforma_BlockList_Details { get; set; }
        public virtual DbSet<BankOfSupplier> BankOfSuppliers { get; set; }
        public virtual DbSet<LCDetail> LCDetails { get; set; }
        public virtual DbSet<PromoItem> PromoItems { get; set; }
        public virtual DbSet<Comparative_Study_Remarks> Comparative_Study_Remarks { get; set; }
        public virtual DbSet<POMaster> POMasters { get; set; }
        public virtual DbSet<Supplier_Categories> Supplier_Categories { get; set; }
        public virtual DbSet<Supplier_Types> Supplier_Types { get; set; }
        public virtual DbSet<BillMaster> BillMasters { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Comparative_Study_Import_Details> Comparative_Study_Import_Details { get; set; }
        public virtual DbSet<MaterialSourceApproval_ChangesHistory> MaterialSourceApproval_ChangesHistory { get; set; }
        public virtual DbSet<MaterialSourceApproval_Remarks> MaterialSourceApproval_Remarks { get; set; }
        public virtual DbSet<MaterialSourceApproval> MaterialSourceApprovals { get; set; }
        public virtual DbSet<PartsAndMachineAccessoriesLog> PartsAndMachineAccessoriesLogs { get; set; }
        public virtual DbSet<Product_ProductionLocations> Product_ProductionLocations { get; set; }
        public virtual DbSet<GRNMaster> GRNMasters { get; set; }
        public virtual DbSet<Supplier_Design_Submit> Supplier_Design_Submit { get; set; }
        public virtual DbSet<BillDist> BillDists { get; set; }
        public virtual DbSet<Comparative_Study> Comparative_Study { get; set; }
        public virtual DbSet<Comparative_Study_Import> Comparative_Study_Import { get; set; }
    }
}
