//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ItemIssue_Details
    {
        public int ID { get; set; }
        public int IssueID { get; set; }
        public int StoreID { get; set; }
        public int RequisitionID { get; set; }
        public int ItemID { get; set; }
        public decimal Quantity { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Inventory_ItemIssues Inventory_ItemIssues { get; set; }
    }
}
