//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Stock_DailyLog
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int ItemID { get; set; }
        public decimal LastStockQuantity { get; set; }
        public decimal Quantity { get; set; }
        public int StockChangeLogID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
