//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Stock_ChangeLogs
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int ItemID { get; set; }
        public int StockUpdateTypeID { get; set; }
        public decimal LastStockQuantity { get; set; }
        public decimal StockInQuantity { get; set; }
        public decimal CurrentStockQuantity { get; set; }
        public decimal StockOutQuantity { get; set; }
        public Nullable<int> QRNID { get; set; }
        public Nullable<int> ConsumptionRequisitionID { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedByID { get; set; }
    
        public virtual Inventory_Stock_ChangeTypes Inventory_Stock_ChangeTypes { get; set; }
    }
}
