//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Quotation_Invitation_Details
    {
        public int ID { get; set; }
        public int QuotationID { get; set; }
        public int RequisitionID { get; set; }
        public int ItemID { get; set; }
        public string SupplierCode { get; set; }
        public string ManufacturerCode { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Inventory_Quotation_Invitations Inventory_Quotation_Invitations { get; set; }
    }
}
