//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Requisitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Requisitions()
        {
            this.Inventory_Requisition_For_Brands = new HashSet<Inventory_Requisition_For_Brands>();
            this.Inventory_Requisition_For_Months = new HashSet<Inventory_Requisition_For_Months>();
            this.Inventory_Requisition_Items = new HashSet<Inventory_Requisition_Items>();
        }
    
        public int ID { get; set; }
        public string RequisitionCode { get; set; }
        public Nullable<int> InventoryTypeID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> RequisitionTypeID { get; set; }
        public string TermAndCondition { get; set; }
        public string Remarks { get; set; }
        public string RecommendedByID { get; set; }
        public Nullable<System.DateTime> RecommendedOn { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerifiedByID { get; set; }
        public string VerifyRemarks { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedById { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string CanceledByID { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string ReasonToCancel { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string ClosedById { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedByID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Requisition_For_Brands> Inventory_Requisition_For_Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Requisition_For_Months> Inventory_Requisition_For_Months { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Requisition_Items> Inventory_Requisition_Items { get; set; }
        public virtual Inventory_Requisition_Type Inventory_Requisition_Type { get; set; }
        public virtual Inventory_Stores Inventory_Stores { get; set; }
    }
}
