//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Purchase_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Purchase_Orders()
        {
            this.Inventory_Purchase_Order_Detail = new HashSet<Inventory_Purchase_Order_Detail>();
        }
    
        public int ID { get; set; }
        public string POCode { get; set; }
        public int MainGroupID { get; set; }
        public string SupplierCode { get; set; }
        public string ManufacturerCode { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int BillPaymentTypeID { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedByID { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string ClosedByID { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public string ClosedRemarks { get; set; }
        public bool IsCanceled { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string CanceledReason { get; set; }
        public string CanceledByID { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string VerifiedByID { get; set; }
        public string VerifiedRemarks { get; set; }
        public string TermsAndConditions { get; set; }
        public string CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> InventoryTypeID { get; set; }
        public Nullable<decimal> CarryingCost { get; set; }
        public Nullable<decimal> LabourCost { get; set; }
        public string OtherCostName { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Purchase_Order_Detail> Inventory_Purchase_Order_Detail { get; set; }
    }
}
