//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_QRN_Items
    {
        public int ID { get; set; }
        public int QRNID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public decimal PassedQuantity { get; set; }
        public decimal RejectedQuantity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Inventory_QRN Inventory_QRN { get; set; }
    }
}
