//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Stock_InTransit
    {
        public int ID { get; set; }
        public Nullable<int> SourceStoreID { get; set; }
        public Nullable<int> DestinationStoreID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> TransferQty { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ReceivedById { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
    }
}
