//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_MainGroup_Users
    {
        public int ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> MainGroupID { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Inventory_Item_MainGroup Inventory_Item_MainGroup { get; set; }
    }
}
