//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_Items
    {


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Items()
        {
            this.Inventory_Item_Versions = new HashSet<Inventory_Item_Versions>();
        }

        public int ID { get; set; }
        public int SubGroupId { get; set; }
        public string ItemCode { get; set; }
        public string GenericName { get; set; }// added ON 18-01-2022
        public decimal Price { get; set; }// added ON 18-01-2022
        public string ItemName { get; set; }
        public string ItemNameWithSpec { get; set; }
        public string Description { get; set; }
        public string UOM { get; set; }
        public decimal MOQ { get; set; }
        public int ItemUsageTypeID { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }

        public virtual Inventory_Item_SubGroup Inventory_Item_SubGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Item_Versions> Inventory_Item_Versions { get; set; }
    }
}
