//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Quotation_Received_Details
    {
        public int ID { get; set; }
        public int QuotationID { get; set; }
        public int ReceiveID { get; set; }
        public int RequisitionID { get; set; }
        public int ItemID { get; set; }
        public string SupplierCode { get; set; }
        public string Currency { get; set; }
        
        public string ManufacturerCode { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<int> BillPaymentTypeID { get; set; }
        public Nullable<int> BillCurrencyTypeID { get; set; }
        
        public string VendorRemarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string SupplierSpecification { get; set; }
        public Nullable<bool> IsSpecificationMatched { get; set; }
        public string RemarksForSupplierSpec { get; set; }
    
        public virtual Inventory_Quotation_Invitations Inventory_Quotation_Invitations { get; set; }
        public virtual Inventory_Quotation_Received Inventory_Quotation_Received { get; set; }
    }
}
