//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_GRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_GRN()
        {
            this.Inventory_GRN_Items = new HashSet<Inventory_GRN_Items>();
            this.Inventory_QRN = new HashSet<Inventory_QRN>();
        }
    
        public int ID { get; set; }
        public string GRNCode { get; set; }
        public string SupplierCode { get; set; }
        public int POID { get; set; }
        public string ChallanNumber { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public int MainGroupID { get; set; }
        public int StoreID { get; set; }
        public string VATChallanNumber { get; set; }
        public Nullable<System.DateTime> VATChallanDate { get; set; }
        public Nullable<bool> IsVDSAllowed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedByID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_GRN_Items> Inventory_GRN_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_QRN> Inventory_QRN { get; set; }
    }
}
