//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Spot_Purchase
    {
        public int ID { get; set; }
        public string PurchaseCode { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string Remarks { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string CanceledRemarks { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
