//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Item_Versions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Item_Versions()
        {
            this.Inventory_Item_Version_Details = new HashSet<Inventory_Item_Version_Details>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<int> VersionStateID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Item_Version_Details> Inventory_Item_Version_Details { get; set; }
        public virtual Inventory_Item_Version_State Inventory_Item_Version_State { get; set; }
        public virtual Inventory_Items Inventory_Items { get; set; }
    }
}
