//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Comparative_Study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Comparative_Study()
        {
            this.Inventory_Comparative_Study_Details = new HashSet<Inventory_Comparative_Study_Details>();
        }
    
        public int ID { get; set; }
        public string CSCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public string CheckedByID { get; set; }
        public Nullable<System.DateTime> CheckedOn { get; set; }
        public string CheckedRemarks { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsManagementApproved { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<bool> IsRecommended { get; set; }
        public string ReviewRemarks { get; set; }
        public Nullable<System.DateTime> ReviewedOn { get; set; }
        public string ReviewedByID { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string VerifiedRemarks { get; set; }
        public string VerifiedByID { get; set; }
        public Nullable<System.DateTime> RecommendedOn { get; set; }
        public string RecommendationRemarks { get; set; }
        public string RecommendedByID { get; set; }
        public Nullable<System.DateTime> ManagementApprovedOn { get; set; }
        public string ManagementApprovedById { get; set; }
        public string ManagementApprovalRemarks { get; set; }
        public Nullable<bool> IsAuditDone { get; set; }
        public string AuditById { get; set; }
        public Nullable<System.DateTime> AuditOn { get; set; }
        public string AuditRemarks { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string ReasonToCancel { get; set; }
        public string CanceledByID { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string RollBackByID { get; set; }
        public string RollBackRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Comparative_Study_Details> Inventory_Comparative_Study_Details { get; set; }
    }
}
