//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LC()
        {
            this.LCDetails = new HashSet<LCDetail>();
        }
    
        public string LCID { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public System.DateTime LastShipDate { get; set; }
        public string Currency { get; set; }
        public decimal ConvRate { get; set; }
        public decimal LCValue { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string SupplierID { get; set; }
        public string BankID { get; set; }
        public string AdvisedBankID { get; set; }
        public string IndenterID { get; set; }
        public string IndentNo { get; set; }
        public string InsuranceNo { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public string LCTT { get; set; }
        public bool IsLocked { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string ClosedBy { get; set; }
        public string ClosedRemarks { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string ReasonToCancel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCDetail> LCDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
