//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterOfCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LetterOfCredit()
        {
            this.LetterOfCredits_Details = new HashSet<LetterOfCredits_Details>();
        }
    
        public int ID { get; set; }
        public string LCCode { get; set; }
        public string LCNumber { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public Nullable<System.DateTime> LastShipmentDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> CurrencyConversionRate { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> AdvisoryBankID { get; set; }
        public Nullable<System.DateTime> PreLCDate { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public string LCType { get; set; }
        public string CreditFacility { get; set; }
        public string IRCNumber { get; set; }
        public string LCAFormNo { get; set; }
        public string InsuranceCoverNote { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBankApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string CanceledBy { get; set; }
        public string CanceledReason { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterOfCredits_Details> LetterOfCredits_Details { get; set; }
    }
}
