//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetail
    {
        public string POID { get; set; }
        public int SLNo { get; set; }
        public string RequisitionID { get; set; }
        public string CSID { get; set; }
        public string MaterialCode { get; set; }
        public string VersionNo { get; set; }
        public string CountryofOrigin { get; set; }
        public string UOM { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal Vat { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalValue { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual POMaster POMaster { get; set; }
        public virtual POReq POReq { get; set; }
    }
}
