//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class POMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POMaster()
        {
            this.PODetails = new HashSet<PODetail>();
        }
    
        public string POID { get; set; }
        public System.DateTime PODate { get; set; }
        public string SupplierID { get; set; }
        public string ManufacturerID { get; set; }
        public string Subject { get; set; }
        public string RequiredFor { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string ModeofPayment { get; set; }
        public string TermsConditions { get; set; }
        public string Currency { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApproveComment { get; set; }
        public Nullable<bool> IsPOClosed { get; set; }
        public string POClosedBy { get; set; }
        public Nullable<System.DateTime> POClosedOn { get; set; }
        public string POClosedRemarks { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsPOCanceled { get; set; }
        public Nullable<System.DateTime> POCanceledOn { get; set; }
        public string POCanceledReason { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string VerifiedBy { get; set; }
        public string VerifiedRemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetail> PODetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
