//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class POReq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POReq()
        {
            this.POReqDetails = new HashSet<POReqDetail>();
            this.PODetails = new HashSet<PODetail>();
        }
    
        public string RequisitionID { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string Raisedby { get; set; }
        public string MaterialGroup { get; set; }
        public string ReqFor { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBY { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedComment { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsPPICGenerated { get; set; }
        public Nullable<byte> RequisitionPriorityStatusID { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string ReasonToCancel { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<bool> IsRequisitionSplitted { get; set; }
        public string SplitRequisitionRemarks { get; set; }
        public string SplittedRequisitionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POReqDetail> POReqDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetail> PODetails { get; set; }
    }
}
