//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class POReqDetail
    {
        public string RequisitionID { get; set; }
        public int SLNo { get; set; }
        public string MaterialCode { get; set; }
        public string VersionNo { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string MaterialGrade { get; set; }
        public string ModeOfShipment { get; set; }
        public string UOM { get; set; }
        public decimal LastStockQty { get; set; }
        public Nullable<int> QuotationInvitationID { get; set; }
        public Nullable<System.DateTime> LastReceivedDate { get; set; }
        public Nullable<decimal> LastPurchaseRate { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<decimal> BaseRequisitionQuantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual POReq POReq { get; set; }
    }
}
