//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProcurementEntities : DbContext
    {
        public ProcurementEntities()
            : base("name=ProcurementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventory_GRN_Items> Inventory_GRN_Items { get; set; }
        public virtual DbSet<Inventory_Item_OpeningBalance> Inventory_Item_OpeningBalance { get; set; }
        public virtual DbSet<Inventory_Item_SubGroup> Inventory_Item_SubGroup { get; set; }
        public virtual DbSet<Inventory_Item_SubGroup_Specifications> Inventory_Item_SubGroup_Specifications { get; set; }
        public virtual DbSet<Inventory_Item_UsageTypes> Inventory_Item_UsageTypes { get; set; }
        public virtual DbSet<Inventory_Item_Version_Details> Inventory_Item_Version_Details { get; set; }
        public virtual DbSet<Inventory_Item_Version_State> Inventory_Item_Version_State { get; set; }
        public virtual DbSet<Inventory_Item_Versions> Inventory_Item_Versions { get; set; }
        public virtual DbSet<Inventory_ItemIssue_Details> Inventory_ItemIssue_Details { get; set; }
        public virtual DbSet<Inventory_ItemIssues> Inventory_ItemIssues { get; set; }
        public virtual DbSet<Inventory_ItemReceive_Acknowledgement> Inventory_ItemReceive_Acknowledgement { get; set; }
        public virtual DbSet<Inventory_ItemReceive_Details> Inventory_ItemReceive_Details { get; set; }
        public virtual DbSet<Inventory_Items> Inventory_Items { get; set; }
        public virtual DbSet<Inventory_Purchase_Order_Detail> Inventory_Purchase_Order_Detail { get; set; }
        public virtual DbSet<Inventory_Purchase_Orders> Inventory_Purchase_Orders { get; set; }
        public virtual DbSet<Inventory_QRN> Inventory_QRN { get; set; }
        public virtual DbSet<Inventory_QRN_Items> Inventory_QRN_Items { get; set; }
        public virtual DbSet<Inventory_Quotation_Invitation_Details> Inventory_Quotation_Invitation_Details { get; set; }
        public virtual DbSet<Inventory_Quotation_Invitations> Inventory_Quotation_Invitations { get; set; }
        public virtual DbSet<Inventory_Quotation_Received> Inventory_Quotation_Received { get; set; }
        public virtual DbSet<Inventory_Quotation_Received_Details> Inventory_Quotation_Received_Details { get; set; }
        public virtual DbSet<Inventory_Requisition_For_Brands> Inventory_Requisition_For_Brands { get; set; }
        public virtual DbSet<Inventory_Requisition_For_Months> Inventory_Requisition_For_Months { get; set; }
        public virtual DbSet<Inventory_Requisition_Items> Inventory_Requisition_Items { get; set; }
        public virtual DbSet<Inventory_Requisition_Type> Inventory_Requisition_Type { get; set; }
        public virtual DbSet<Inventory_Stock> Inventory_Stock { get; set; }
        public virtual DbSet<Inventory_Stock_ChangeLogs> Inventory_Stock_ChangeLogs { get; set; }
        public virtual DbSet<Inventory_Stock_ChangeTypes> Inventory_Stock_ChangeTypes { get; set; }
        public virtual DbSet<Inventory_Stock_DailyLog> Inventory_Stock_DailyLog { get; set; }
        public virtual DbSet<Inventory_Stores> Inventory_Stores { get; set; }
        public virtual DbSet<Inventory_Types> Inventory_Types { get; set; }
        public virtual DbSet<Inventory_TypesAndStore> Inventory_TypesAndStore { get; set; }
        public virtual DbSet<Inventory_UserStores> Inventory_UserStores { get; set; }
        public virtual DbSet<UnitOfMeasurement> UnitOfMeasurements { get; set; }
        public virtual DbSet<Inventory_Item_Specification> Inventory_Item_Specification { get; set; }
        public virtual DbSet<Inventory_Item_MainGroup> Inventory_Item_MainGroup { get; set; }
        public virtual DbSet<Inventory_SubGroup_Suppliers> Inventory_SubGroup_Suppliers { get; set; }
        public virtual DbSet<Inventory_MainGroup_Users> Inventory_MainGroup_Users { get; set; }
        public virtual DbSet<Inventory_Stock_Opening> Inventory_Stock_Opening { get; set; }
        public virtual DbSet<Inventory_Stock_InTransit> Inventory_Stock_InTransit { get; set; }
        public virtual DbSet<Inventory_Requisitions> Inventory_Requisitions { get; set; }
        public virtual DbSet<Inventory_GRN> Inventory_GRN { get; set; }
    }
}
