//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProformaInvoice()
        {
            this.ProformaInvoice_Details = new HashSet<ProformaInvoice_Details>();
        }
    
        public int ID { get; set; }
        public string PICode { get; set; }
        public string PINumber { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public string OriginOfGoods { get; set; }
        public string PackingInfo { get; set; }
        public string TransShipment { get; set; }
        public string PartShipment { get; set; }
        public string ShelfLife { get; set; }
        public string DocumentsForExporter { get; set; }
        public string Payment { get; set; }
        public string Delivery { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DeliveryTerm { get; set; }
        public string PortOfShipment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaInvoice_Details> ProformaInvoice_Details { get; set; }
    }
}
