//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proforma_BlockList_Details
    {
        public int ID { get; set; }
        public Nullable<int> BlockListID { get; set; }
        public string MaterialCode { get; set; }
        public string SupplierCode { get; set; }
        public string ManufacturerCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> CurrencyConversionRate { get; set; }
        public string FinishGoodProductName { get; set; }
        public Nullable<decimal> LastYearImportQuantity { get; set; }
        public Nullable<decimal> CurrentYearImportQuantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string CountryName { get; set; }
        public string UOM { get; set; }
        public string Remarks { get; set; }
        public string DMLInclude { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> LastYearFinishGoodQuantity { get; set; }
        public Nullable<decimal> CurrentYearApprovedQuantity { get; set; }
        public string RequisitionCode { get; set; }
        public string ModeOfShipment { get; set; }
    
        public virtual Proforma_BlockList Proforma_BlockList { get; set; }
    }
}
