//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaInvoice_Invitation_Details
    {
        public int ID { get; set; }
        public Nullable<int> PIID { get; set; }
        public Nullable<int> CSID { get; set; }
        public string RequisitionCode { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ProformaInvoice_Invitation ProformaInvoice_Invitation { get; set; }
    }
}
