//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoItem
    {
        public int ID { get; set; }
        public string PromoCode { get; set; }
        public Nullable<int> SubGroupID { get; set; }
        public string ItemName { get; set; }
        public string UOM { get; set; }
        public string PackSize { get; set; }
        public string Specification { get; set; }
        public string LeadTime { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
