//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionFollowUp
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string MaterialCode { get; set; }
        public string RequisitionCode { get; set; }
        public string RemarksFromFactory { get; set; }
        public Nullable<System.DateTime> TentativeAvailableDate { get; set; }
        public string RemarksFromSCM { get; set; }
        public Nullable<System.DateTime> ActualAvailableDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
