//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCMEntities : DbContext
    {
        public SCMEntities()
            : base("name=SCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LetterOfCredit> LetterOfCredits { get; set; }
        public virtual DbSet<LetterOfCredits_Details> LetterOfCredits_Details { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<POReq> POReqs { get; set; }
        public virtual DbSet<POReqDetail> POReqDetails { get; set; }
        public virtual DbSet<Quotation_Invitation_Details> Quotation_Invitation_Details { get; set; }
        public virtual DbSet<Quotation_Invitation_Import_Details> Quotation_Invitation_Import_Details { get; set; }
        public virtual DbSet<Quotation_Invitations> Quotation_Invitations { get; set; }
        public virtual DbSet<Quotation_Invitations_Import> Quotation_Invitations_Import { get; set; }
        public virtual DbSet<Quotation_Received> Quotation_Received { get; set; }
        public virtual DbSet<Quotation_Received_Details> Quotation_Received_Details { get; set; }
        public virtual DbSet<Quotation_Received_Import> Quotation_Received_Import { get; set; }
        public virtual DbSet<Quotation_Received_Import_Details> Quotation_Received_Import_Details { get; set; }
        public virtual DbSet<LC> LCs { get; set; }
        public virtual DbSet<LCDetail> LCDetails { get; set; }
        public virtual DbSet<PODetail> PODetails { get; set; }
        public virtual DbSet<POMaster> POMasters { get; set; }
        public virtual DbSet<GRNDetail> GRNDetails { get; set; }
        public virtual DbSet<GRNMaster> GRNMasters { get; set; }
        public virtual DbSet<Comparative_Study_Internal_Approval> Comparative_Study_Internal_Approval { get; set; }
        public virtual DbSet<Comparative_Study_Internal_Approval_Details> Comparative_Study_Internal_Approval_Details { get; set; }
        public virtual DbSet<Comparative_Study_Import_InternalApproval> Comparative_Study_Import_InternalApproval { get; set; }
        public virtual DbSet<Comparative_Study_Import_InternalApproval_Details> Comparative_Study_Import_InternalApproval_Details { get; set; }
        public virtual DbSet<Comparative_Study_Remarks> Comparative_Study_Remarks { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Comparative_Study_StatusComment> Comparative_Study_StatusComment { get; set; }
        public virtual DbSet<Inventory_Comparative_Study> Inventory_Comparative_Study { get; set; }
        public virtual DbSet<LC_StatusComment> LC_StatusComment { get; set; }
        public virtual DbSet<Comparative_Study_Import_Details> Comparative_Study_Import_Details { get; set; }
        public virtual DbSet<Comparative_Study_Import> Comparative_Study_Import { get; set; }
        public virtual DbSet<Comparative_Study> Comparative_Study { get; set; }
        public virtual DbSet<Comparative_Study_Details> Comparative_Study_Details { get; set; }
    }
}
