//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupplierEntities : DbContext
    {
        public SupplierEntities()
            : base("name=SupplierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Supplier_Design_Submit> Supplier_Design_Submit { get; set; }
        public virtual DbSet<Supplier_TDS> Supplier_TDS { get; set; }
        public virtual DbSet<SupplierDesign_StatusReport> SupplierDesign_StatusReport { get; set; }
        public virtual DbSet<SupplierDesign_StatusReport_Message> SupplierDesign_StatusReport_Message { get; set; }
    }
}
