//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDesign_StatusReport_Message
    {
        public int ID { get; set; }
        public Nullable<int> StatusReportID { get; set; }
        public string NotifyMessage { get; set; }
        public string NotifyPersonName { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
    }
}
