//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.LCs = new HashSet<LC>();
            this.POMasters = new HashSet<POMaster>();
        }
    
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string Address { get; set; }
        public string SupplierType { get; set; }
        public string SupplierCategory { get; set; }
        public string ContactPerson { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Webaddress { get; set; }
        public string Remarks { get; set; }
        public string Location { get; set; }
        public string MachineNameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int ID { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
        public Nullable<int> SupplierCategoryID { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<System.DateTime> CanceledOn { get; set; }
        public string CanceledByID { get; set; }
        public string CanceledRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LC> LCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POMaster> POMasters { get; set; }
    }
}
