//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemManagerEntities : DbContext
    {
        public SystemManagerEntities()
            : base("name=SystemManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationList> ApplicationLists { get; set; }
        public virtual DbSet<Default_Application_Department> Default_Application_Department { get; set; }
        public virtual DbSet<Default_Application_User> Default_Application_User { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<Web_Applications> Web_Applications { get; set; }
        public virtual DbSet<Web_MenuBrowsing_History> Web_MenuBrowsing_History { get; set; }
        public virtual DbSet<Web_MenuRequestLog> Web_MenuRequestLog { get; set; }
        public virtual DbSet<Web_Menus> Web_Menus { get; set; }
        public virtual DbSet<Web_UserFavoriteMenus> Web_UserFavoriteMenus { get; set; }
        public virtual DbSet<Web_UserPrivileges> Web_UserPrivileges { get; set; }
        public virtual DbSet<v_ApplicationMenus> v_ApplicationMenus { get; set; }
        public virtual DbSet<v_WebApplicationMenus> v_WebApplicationMenus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Notification_Module> Notification_Module { get; set; }
        public virtual DbSet<Notification_ModuleRecepients> Notification_ModuleRecepients { get; set; }
        public virtual DbSet<WebTokenManager> WebTokenManagers { get; set; }
        public virtual DbSet<User_Complain_Recepients> User_Complain_Recepients { get; set; }
        public virtual DbSet<User_Complain_Types> User_Complain_Types { get; set; }
        public virtual DbSet<User_Complain_Actions> User_Complain_Actions { get; set; }
        public virtual DbSet<User_Complain_Attachments> User_Complain_Attachments { get; set; }
        public virtual DbSet<User_Complain_SolutionStatus> User_Complain_SolutionStatus { get; set; }
        public virtual DbSet<Web_UserDevices> Web_UserDevices { get; set; }
        public virtual DbSet<Web_Menu_Privilege_Group> Web_Menu_Privilege_Group { get; set; }
        public virtual DbSet<User_Complains> User_Complains { get; set; }
    }
}
