//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Complain_SolutionStatus
    {
        public int ID { get; set; }
        public string SolutionStatusName { get; set; }
        public bool IsActive { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
