//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Complains
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Complains()
        {
            this.User_Complain_Actions = new HashSet<User_Complain_Actions>();
            this.User_Complain_Attachments = new HashSet<User_Complain_Attachments>();
            this.User_Complain_Recepients = new HashSet<User_Complain_Recepients>();
        }
    
        public int ID { get; set; }
        public int UserComplainTypeID { get; set; }
        public string Details { get; set; }
        public string Recepients { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public Nullable<System.DateTime> SolvedOn { get; set; }
        public Nullable<int> SolvedByID { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Complain_Actions> User_Complain_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Complain_Attachments> User_Complain_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Complain_Recepients> User_Complain_Recepients { get; set; }
        public virtual User_Complain_Types User_Complain_Types { get; set; }
    }
}
