//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Complain_Recepients
    {
        public int ID { get; set; }
        public int ComplainID { get; set; }
        public int RecepientID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsSeen { get; set; }
    
        public virtual User_Complains User_Complains { get; set; }
    }
}
