//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_UserPrivileges
    {
        public int PrivilegeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<bool> HasView { get; set; }
        public Nullable<bool> HasInsert { get; set; }
        public Nullable<bool> HasUpdate { get; set; }
        public Nullable<bool> HasDelete { get; set; }
        public Nullable<bool> HasPrint { get; set; }
        public Nullable<bool> HasFullAccess { get; set; }
        public Nullable<bool> HasReview { get; set; }
        public Nullable<bool> HasVerify { get; set; }
        public Nullable<bool> HasApprove { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsVisited { get; set; }
        public Nullable<bool> HasRecommendation { get; set; }
        public Nullable<bool> HasCheck { get; set; }
        public Nullable<bool> HasAudit { get; set; }
    
        public virtual Web_Menus Web_Menus { get; set; }
    }
}
