//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Menu_Privilege_Group
    {
        public int ID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<bool> HasView { get; set; }
        public Nullable<bool> HasInsert { get; set; }
        public Nullable<bool> HasUpdate { get; set; }
        public Nullable<bool> HasDelete { get; set; }
        public Nullable<bool> HasPrint { get; set; }
        public Nullable<bool> HasReview { get; set; }
        public Nullable<bool> HasVerify { get; set; }
        public Nullable<bool> HasRecommendation { get; set; }
        public Nullable<bool> HasApprove { get; set; }
        public Nullable<bool> HasFullAccess { get; set; }
    }
}
