//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebERPAPI.Data.Models.PROCESSERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_UserDevices
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string User_GUID { get; set; }
        public string IPAddress { get; set; }
        public string DeviceDetails { get; set; }
        public string LocationDetails { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastLoggedOn { get; set; }
    }
}
