//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public int ApplicationID { get; set; }
        public string UserCode { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
