//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bak_VWTargetInfo
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public string TerritoryID { get; set; }
        public string TerritoryName { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string ProductID { get; set; }
        public string productName { get; set; }
        public string PackSize { get; set; }
        public Nullable<decimal> TradePrice { get; set; }
        public Nullable<int> TargetQty { get; set; }
        public string AreaID { get; set; }
        public string AreaName { get; set; }
        public string ASMID { get; set; }
        public string ASMName { get; set; }
        public string RegionID { get; set; }
        public string RegionName { get; set; }
        public string RSMID { get; set; }
        public string RSMName { get; set; }
    }
}
