//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Uploads
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string SignatureFilename { get; set; }
        public string ProfileImagename { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
