//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<WHIssue> WHIssues { get; set; }
        public virtual DbSet<BillDetail> BillDetails { get; set; }
        public virtual DbSet<BillMaster> BillMasters { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Bill_Payment_Status> Bill_Payment_Status { get; set; }
        public virtual DbSet<Bill_PaymentType> Bill_PaymentType { get; set; }
        public virtual DbSet<Bill_Payment_Details> Bill_Payment_Details { get; set; }
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<POReq> POReqs { get; set; }
        public virtual DbSet<Quotation_Invitation_Details> Quotation_Invitation_Details { get; set; }
        public virtual DbSet<Quotation_Invitations> Quotation_Invitations { get; set; }
    }
}
