//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemManagerEntities : DbContext
    {
        public SystemManagerEntities()
            : base("name=SystemManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<UserLocation> UserLocations { get; set; }
        public virtual DbSet<Web_Menus> Web_Menus { get; set; }
        public virtual DbSet<Web_UserPrivileges> Web_UserPrivileges { get; set; }
        public virtual DbSet<v_ApplicationMenus> v_ApplicationMenus { get; set; }
        public virtual DbSet<v_WebApplicationMenus> v_WebApplicationMenus { get; set; }
        public virtual DbSet<Web_UserLogDetails> Web_UserLogDetails { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
