//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POReq
    {
        public string RequisitionID { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string Raisedby { get; set; }
        public string ReqFor { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBY { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedComment { get; set; }
        public string Location { get; set; }
        public string MachinenameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
