//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionTarget
    {
        public int YearNo { get; set; }
        public int MonthNo { get; set; }
        public string MonthName { get; set; }
        public string WorkAreaType { get; set; }
        public string WorkAreaID { get; set; }
        public string WorkAreaName { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public decimal TargetQty { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
