//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int OrderNo { get; set; }
        public string ChemistID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryShift { get; set; }
        public string EmployeeID { get; set; }
        public string MobileNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceType { get; set; }
        public string DepoID { get; set; }
        public string DAID { get; set; }
        public string FileName { get; set; }
        public bool IsApproved { get; set; }
        public bool IsProblem { get; set; }
        public string Error { get; set; }
        public bool IsLocked { get; set; }
        public string Location { get; set; }
        public string MachineNameIP { get; set; }
        public bool Transfered { get; set; }
        public bool HOTransfered { get; set; }
        public string Addedby { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
