//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Return_detail
    {
        public System.DateTime InvoiceDate { get; set; }
        public string ChemistID { get; set; }
        public string ChemistName { get; set; }
        public string ChemistAddress { get; set; }
        public string DAID { get; set; }
        public string DepotID { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<decimal> Receivable { get; set; }
        public string InvoiceID { get; set; }
        public string ProductID { get; set; }
        public string BrandName { get; set; }
        public string PackSize { get; set; }
        public decimal Tradeprice { get; set; }
        public decimal Vat { get; set; }
        public Nullable<decimal> orderQuantity { get; set; }
        public Nullable<decimal> TransitQty { get; set; }
        public Nullable<decimal> TransitBonus { get; set; }
        public Nullable<decimal> SoldQty { get; set; }
        public Nullable<decimal> SBonusQty { get; set; }
        public Nullable<decimal> ReturnQuantity { get; set; }
        public Nullable<decimal> BonusReturnQty { get; set; }
        public Nullable<decimal> SID_DAmount { get; set; }
        public Nullable<decimal> STotalTP { get; set; }
        public Nullable<decimal> STotalVat { get; set; }
        public Nullable<decimal> PD { get; set; }
        public string TerritoryID { get; set; }
        public string TerritoryName { get; set; }
        public string EmployeeID { get; set; }
        public string AreaID { get; set; }
        public string AreaName { get; set; }
        public string RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<decimal> ccReturnQty { get; set; }
        public Nullable<decimal> ccReturnTP { get; set; }
        public Nullable<decimal> ccReturnVat { get; set; }
        public Nullable<decimal> ccReturnDiscount { get; set; }
        public bool Transfered { get; set; }
    }
}
