//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaidERP.Data.PROCESS_SERVER_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Menus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Web_Menus()
        {
            this.Web_UserPrivileges = new HashSet<Web_UserPrivileges>();
        }
    
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Route { get; set; }
        public Nullable<bool> ShowingStatus { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public Nullable<bool> IsNonPrivilegedMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_UserPrivileges> Web_UserPrivileges { get; set; }
    }
}
